<?xml version="1.0" encoding="ISO-8859-1" standalone="yes"?>
<!-- 
  File   : voms.xml 
  Author : Piter T. de Boer 
  Info   : 
  
       Additional VOMS servers information. 
       This file will also be scanned in addition to possible other voms.xml files. 
           
       Current search order for VO information is (first matched, first used):  
        - User Configuration : $HOME/.globus/vomsdir/voms.xml
        - Installation       : $VLET_INSTALL/etc/voms.xml 
        - GLobus (host)      : /etc/grid-security/vomsdir/voms.xml           
-->

<!DOCTYPE voms[
  <!ELEMENT name (#PCDATA)>
  <!ELEMENT admin (#PCDATA)>
  <!ELEMENT port (#PCDATA)>
  <!ELEMENT cert (#PCDATA)>
  <!ELEMENT dn (#PCDATA)>
  <!ELEMENT server (name,port,cert,dn)>
  <!ELEMENT vo (name,admin,server*)>
  <!ELEMENT voms (vo*)>
]>

<!--
  PLEASE NOTE!!!

  If you edit this file, please note the form of the Email part of the DN (if it exists)
  This is a Globus / BouncyCastle / Java consistency problem

  The reason to have a seaming repeat of the name/cert for each server is because the cert
  is a filename and can be changed - and often is on a standard UI... 
  this file is designed so it can be added into an existing UI as well as within a purely acacia environment.
-->

<!-- 
   =================
   EGI/Dutchgrid VOMS Servers
   =================
   See:   https://voms.grid.sara.nl:8443/vomses
	   
	"alice" "lcg-voms.cern.ch" "15000" "/DC=ch/DC=cern/OU=computers/CN=lcg-voms.cern.ch" "alice" "24"
	"alice" "voms.cern.ch" "15000" "/DC=ch/DC=cern/OU=computers/CN=voms.cern.ch" "alice" "24"
	"appsportal.nl" "voms.grid.sara.nl" "30026" "/O=dutchgrid/O=hosts/OU=sara.nl/CN=voms.grid.sara.nl" "appsportal.nl"
	"atlas" "lcg-voms.cern.ch" "15001" "/DC=ch/DC=cern/OU=computers/CN=lcg-voms.cern.ch" "atlas" "24"
	"atlas" "voms.cern.ch" "15001" "/DC=ch/DC=cern/OU=computers/CN=voms.cern.ch" "atlas" "24"
	"atlas" "vo.racf.bnl.gov" "15003" "/DC=org/DC=doegrids/OU=Services/CN=vo.racf.bnl.gov" "atlas" "24"
	"bbmri.nl" "voms.grid.sara.nl" "30011" "/O=dutchgrid/O=hosts/OU=sara.nl/CN=voms.grid.sara.nl" "bbmri.nl"
	"beapps" "voms01.begrid.be" "18004" "/C=BE/O=BEGRID/OU=BEgrid/OU=BELNET/CN=voms01.begrid.be" "beapps" "24"
	"beapps" "voms02.begrid.be" "18004" "/C=BE/O=BEGRID/OU=BEgrid/OU=BELNET/CN=voms02.begrid.be" "beapps" "24"
	"beapps" "voms.begrid.be" "18004" "/C=BE/O=BEGRID/OU=BEgrid/OU=BELNET/CN=voms.begrid.be" "beapps"
	"biomed" "cclcgvomsli01.in2p3.fr" "15000" "/O=GRID-FR/C=FR/O=CNRS/OU=CC-IN2P3/CN=cclcgvomsli01.in2p3.fr" "biomed" "24"
	"compchem" "voms.cnaf.infn.it" "15003" "/C=IT/O=INFN/OU=Host/L=CNAF/CN=voms.cnaf.infn.it" "/C=IT/O=INFN/OU=Host/L=CNAF/CN=voms.cnaf.infn.it"
	"dans" "voms.grid.sara.nl" "30016" "/O=dutchgrid/O=hosts/OU=sara.nl/CN=voms.grid.sara.nl" "dans"
	"dteam" "voms2.hellasgrid.gr" "15004" "/C=GR/O=HellasGrid/OU=hellasgrid.gr/CN=voms2.hellasgrid.gr" "dteam" "24"
	"dteam" "voms.hellasgrid.gr" "15004" "/C=GR/O=HellasGrid/OU=hellasgrid.gr/CN=voms.hellasgrid.gr" "dteam" "24"
	"dzero" "voms.fnal.gov" "15002" "/DC=org/DC=doegrids/OU=Services/CN=http/voms.fnal.gov" "dzero"
	"emutd" "voms.grid.sara.nl" "30010" "/O=dutchgrid/O=hosts/OU=sara.nl/CN=voms.grid.sara.nl" "emutd"
	"esr" "voms.grid.sara.nl" "30001" "/O=dutchgrid/O=hosts/OU=sara.nl/CN=voms.grid.sara.nl" "esr"
	"gaussian" "voms.cyf-kr.edu.pl" "15001" "/C=PL/O=GRID/O=Cyfronet/CN=voms.cyf-kr.edu.pl" "gaussian"
	"geant4" "voms.cern.ch" "15007" "/DC=ch/DC=cern/OU=computers/CN=lcg-voms.cern.ch" "geant4"
	"lhcb" "lcg-voms.cern.ch" "15003" "/DC=ch/DC=cern/OU=computers/CN=lcg-voms.cern.ch" "lhcb" "24"
	"lhcb" "voms.cern.ch" "15003" "/DC=ch/DC=cern/OU=computers/CN=voms.cern.ch" "lhcb" "24"
	"lofar" "voms.grid.sara.nl" "30019" "/O=dutchgrid/O=hosts/OU=sara.nl/CN=voms.grid.sara.nl" "lofar"
	"lsgrid" "voms.grid.sara.nl" "30018" "/O=dutchgrid/O=hosts/OU=sara.nl/CN=voms.grid.sara.nl" "lsgrid"
	"ncf" "voms.grid.sara.nl" "30014" "/O=dutchgrid/O=hosts/OU=sara.nl/CN=voms.grid.sara.nl" "ncf"
	"nlesc.nl" "voms.grid.sara.nl" "30025" "/O=dutchgrid/O=hosts/OU=sara.nl/CN=voms.grid.sara.nl" "nlesc.nl"
	"omegac" "voms.grid.sara.nl" "30020" "/O=dutchgrid/O=hosts/OU=sara.nl/CN=voms.grid.sara.nl" "omegac"
	"ops" "lcg-voms.cern.ch" "15009" "/DC=ch/DC=cern/OU=computers/CN=lcg-voms.cern.ch" "ops" "24"
	"ops" "voms.cern.ch" "15004" "/DC=ch/DC=cern/OU=computers/CN=voms.cern.ch" "ops" "24"
	"pheno" "voms.gridpp.ac.uk" "15011" "/C=UK/O=eScience/OU=Manchester/L=HEP/CN=voms.gridpp.ac.uk" "pheno"
	"phicos" "voms.grid.sara.nl" "30009" "/O=dutchgrid/O=hosts/OU=sara.nl/CN=voms.grid.sara.nl" "phicos"
	"pvier" "voms.grid.sara.nl" "30000" "/O=dutchgrid/O=hosts/OU=sara.nl/CN=voms.grid.sara.nl" "pvier"
	"saradmins" "voms.grid.sara.nl" "30023" "/O=dutchgrid/O=hosts/OU=sara.nl/CN=voms.grid.sara.nl" "saradmins"
	"scia" "voms.grid.sara.nl" "30021" "/O=dutchgrid/O=hosts/OU=sara.nl/CN=voms.grid.sara.nl" "scia"
	"shiwa-workflow.eu" "cclcgvomsli01.in2p3.fr" "15016" "/O=GRID-FR/C=FR/O=CNRS/OU=CC-IN2P3/CN=cclcgvomsli01.in2p3.fr" "shiwa-workflow.eu" "24"
	"test_vo" "voms.grid.sara.nl" "30017" "/O=dutchgrid/O=hosts/OU=sara.nl/CN=voms.grid.sara.nl" "test_vo"
	"tutor" "voms.grid.sara.nl" "30007" "/O=dutchgrid/O=hosts/OU=sara.nl/CN=voms.grid.sara.nl" "tutor"
	"vldbi" "voms.grid.sara.nl" "30006" "/O=dutchgrid/O=hosts/OU=sara.nl/CN=voms.grid.sara.nl" "vldbi"
	"vlefi" "voms.grid.sara.nl" "30004" "/O=dutchgrid/O=hosts/OU=sara.nl/CN=voms.grid.sara.nl" "vlefi"
	"vlemed" "voms.grid.sara.nl" "30003" "/O=dutchgrid/O=hosts/OU=sara.nl/CN=voms.grid.sara.nl" "vlemed"
	"vlibu" "voms.grid.sara.nl" "30002" "/O=dutchgrid/O=hosts/OU=sara.nl/CN=voms.grid.sara.nl" "vlibu"

   
--> 

<voms> 

 <!-- Dutchgrid VOs -->
 
 <vo>
  <name>pvier</name>
  <admin>https://voms.grid.sara.nl:8443/voms/pvier/webui/admin</admin>
  <server>
     <name>voms.grid.sara.nl</name>
     <port>30000</port>
     <cert>voms.grid.sara.nl.1304</cert>
     <dn>/O=dutchgrid/O=hosts/OU=sara.nl/CN=voms.grid.sara.nl</dn>
  </server>
 </vo>
 
 <vo>
  <name>vlibu</name>
  <admin>https://voms.grid.sara.nl:8443/voms/vlibu/webui/admin</admin>
  <server>
     <name>voms.grid.sara.nl</name>
     <port>30002</port>
     <cert>voms.grid.sara.nl.1304</cert>
     <dn>/O=dutchgrid/O=hosts/OU=sara.nl/CN=voms.grid.sara.nl</dn>
  </server>
 </vo>

 <vo>
   <name>vlemed</name>
   <admin>https://voms.grid.sara.nl:8443/voms/vlemed/webui/admin</admin>
   <server>
     <name>voms.grid.sara.nl</name>
     <port>30003</port>
     <cert>voms.grid.sara.nl.1304</cert>
     <dn>/O=dutchgrid/O=hosts/OU=sara.nl/CN=voms.grid.sara.nl</dn>
   </server>
 </vo>
 
 <vo>
   <name>vlefi</name>
   <admin>https://voms.grid.sara.nl:8443/voms/vlefi/webui/admin</admin>
   <server>
     <name>voms.grid.sara.nl</name>
     <port>30004</port>
     <cert>voms.grid.sara.nl.1304</cert>
     <dn>/O=dutchgrid/O=hosts/OU=sara.nl/CN=voms.grid.sara.nl</dn>
   </server>
 </vo>

 <vo>
   <name>vledut</name>
   <admin>https://voms.grid.sara.nl:8443/voms/vledut/webui/admin</admin>
   <server>
     <name>voms.grid.sara.nl</name>
     <port>30005</port>
     <cert>voms.grid.sara.nl.1304</cert>
     <dn>/O=dutchgrid/O=hosts/OU=sara.nl/CN=voms.grid.sara.nl</dn>
   </server>
 </vo>

 <vo>
   <name>vledbi</name>
   <admin>https://voms.grid.sara.nl:8443/voms/vledbi/webui/admin</admin>
   <server>
     <name>voms.grid.sara.nl</name>
     <port>30006</port>
     <cert>voms.grid.sara.nl.1304</cert>
     <dn>/O=dutchgrid/O=hosts/OU=sara.nl/CN=voms.grid.sara.nl</dn>
   </server>
 </vo>
 
  <vo>
   <name>phicos</name>
   <admin>https://voms.grid.sara.nl:8443/voms/phicos/webui/admin</admin>
   <server>
     <name>voms.grid.sara.nl</name>
     <port>30006</port>
     <cert>voms.grid.sara.nl.1304</cert>
     <dn>/O=dutchgrid/O=hosts/OU=sara.nl/CN=voms.grid.sara.nl</dn>
   </server>
 </vo>
 
   <vo>
   <name>ncf</name>
   <admin>https://voms.grid.sara.nl:8443/voms/ncf/webui/admin</admin>
   <server>
     <name>voms.grid.sara.nl</name>
     <port>30014</port>
     <cert>voms.grid.sara.nl.1304</cert>
     <dn>/O=dutchgrid/O=hosts/OU=sara.nl/CN=voms.grid.sara.nl</dn>
   </server>
 </vo>
 
  
 <vo>
   <name>dans</name>
   <admin>https://voms.grid.sara.nl:8443/voms/dans/webui/admin</admin>
   <server>
     <name>voms.grid.sara.nl</name>
     <port>30016</port>
     <cert>voms.grid.sara.nl.1304</cert>
     <dn>/O=dutchgrid/O=hosts/OU=sara.nl/CN=voms.grid.sara.nl</dn>
   </server>
 </vo>
 
 <vo>
   <name>dans</name>
   <admin>https://voms.grid.sara.nl:8443/voms/dans/webui/admin</admin>
   <server>
     <name>voms.grid.sara.nl</name>
     <port>30016</port>
     <cert>voms.grid.sara.nl.1304</cert>
     <dn>/O=dutchgrid/O=hosts/OU=sara.nl/CN=voms.grid.sara.nl</dn>
   </server>
 </vo>

 <vo>
   <name>lsgrid</name>
   <admin>https://voms.grid.sara.nl:8443/voms/lsgrid/webui/admin</admin>
   <server>
     <name>voms.grid.sara.nl</name>
     <port>30018</port>
     <cert>voms.grid.sara.nl.1304</cert>
     <dn>/O=dutchgrid/O=hosts/OU=sara.nl/CN=voms.grid.sara.nl</dn>
   </server>
 </vo>
 
 <vo>
   <name>lofar</name>
   <admin>https://voms.grid.sara.nl:8443/voms/lofar/webui/admin</admin>
   <server>
     <name>voms.grid.sara.nl</name>
     <port>30019</port>
     <cert>voms.grid.sara.nl.1304</cert>
     <dn>/O=dutchgrid/O=hosts/OU=sara.nl/CN=voms.grid.sara.nl</dn>
   </server>
 </vo>
 
  <!-- Netherlands eScience Center --> 
 
  <vo>
   <name>nlesc.nl</name>
   <admin>https://voms.grid.sara.nl:8443/voms/nlesc.nl/webui/admin</admin>
   <server>
     <name>voms.grid.sara.nl</name>
     <port>30025</port>
     <cert>voms.grid.sara.nl.1304</cert>
     <dn>/O=dutchgrid/O=hosts/OU=sara.nl/CN=voms.grid.sara.nl</dn>
   </server>
 </vo>
 <!-- 
   ===========================================================================
      BIOMED france
   ===========================================================================
   --> 
  
<vo>
  <name>biomed</name>
  <admin>https://cclcgvomsli01.in2p3.fr:8443/voms/biomed</admin>
  <server>
    <name>cclcgvomsli01.in2p3.fr</name>
    <port>15000</port>
    <cert>cclcgvomsli01.in2p3.fr.4786.pem</cert>
    <dn>/O=GRID-FR/C=FR/O=CNRS/OU=CC-LYON/CN=cclcgvomsli01.in2p3.fr</dn>
  </server>
</vo> 

 <!-- 
   ===========================================================================
      LCG DTEAM
   ===========================================================================
   --> 

<vo>
  <name>dteam</name>
  <admin>https://voms2.hellasgrid.gr:15004/voms/dteam</admin>
  <server>
    <name>voms2.hellasgrid.gr</name>
    <port>15004</port>
    <cert>voms2.hellasgrid.gr.pem</cert>
    <dn>/C=GR/O=HellasGrid/OU=hellasgrid.gr/CN=voms2.hellasgrid.gr</dn>
  </server>
</vo> 

</voms>
